services:
  - type: web
    name: student-management-system
    runtime: python
    rootDir: student_management_system
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
